### ISSUE TITLE
Outdated repo

### ISSUE THREAD

**Issue by camiloforero** [MSG91/msg91-ruby#1]
This repo shows the code and instructions for the 0.1.0 version of the gem, while the one available at rubygems is 0.2.2.

That makes using this gem unintuitive, as we must either purposefully install v 0.1.0 or dig the readme from the downloaded gem and use those instructions.

The latest version of the source code should be uploaded here

**Comment by 31piy** [comment]
This repo has not made to the rubygems repository yet. All the available versions there are not officially supported. Those are published by individual contributors.

**Comment by camiloforero** [comment]
The `README.md` instructions in this repo instruct the users to install the `msg91` gem from the rubygems repository. If that gems are unrelated to this repo, then you shouldn't be referencing it from here,

**Comment by 31piy** [comment]
@camiloforero -- Thanks! I've updated the installation instructions for this gem.
